<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.16">
  <POU Name="MAIN" Id="{7c37925b-362c-4ebf-880c-ca7e46ea3b81}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
    Carro: FB_Carro_DRC_LD;
    // Carro: FB_Carro_GRF_SFC;
    // Carro: FB_Carro_GRF_ST;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[Carro();
]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>